### ISSUE TITLE
System.Threading.Timer

### ISSUE THREAD

**Issue by NikKOo31** [Ryzhehvost/BoosterCreator#1]
I'm new using ASF plugins. I couldn't find a fix for this

```
2020-02-01 14:00:38|ArchiSteamFarm-8764|FATAL|ASF|OnUnhandledException() System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Timer, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Threading.Timer, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at BoosterCreator.BoosterHandler..ctor(Bot bot, IReadOnlyCollection`1 gameIDs)
   at BoosterCreator.BoosterCreator.<>c__DisplayClass6_1.<OnBotInitModules>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary`2 additionalConfigProperties)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Thanks in advance for any help! :)

**Comment by Ryzhehvost** [comment]
Thank you for your report! 
This issue was already resolved in ASF itself https://github.com/JustArchiNET/ArchiSteamFarm/commit/7078644b7d3a7b10cc0e7dfd06d82149fb19dda5
Plugin will work in next ASF version, you may manually update to latest ASF pre-release if you need this feature right now.
