### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by woctezuma** [Ryzhehvost/BoosterCreator#14]
```
ArchiSteamFarm V5.2.5.5 (generic/ff9c19de-593f-4213-b31d-4e09469e6931 | .NET 6.0.4; win10-x64)
```
```
ERROR|ASF|OnBotInitModules() System.MissingMethodException: Method not found: 'Void ArchiSteamFarm.NLog.ArchiLogger.LogNullError(System.String, System.String)'.
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary`2 additionalConfigProperties)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass21_0.<OnBotInitModules>b__0(IBotModules plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotInitModules(Bot bot, IReadOnlyDictionary`2 additionalConfigProperties)
```

**Comment by woctezuma** [comment]
Related:
- #8 
- #9 

However, I am using `generic` ASF.

**Comment by Ryzhehvost** [comment]
Thank you for the report, I'll check it.

**Comment by woctezuma** [comment]
Wait, I realize that I am not using the latest version of the plugin!

**Comment by woctezuma** [comment]
I still have this issue. What is strange is that it seems that I am still using v.1.2.1.0 despite downloading the latest version v.1.2.2.0.

```
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() Chargement BoosterCreator V1.2.1.0...
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|OnLoaded() BoosterCreator ASF Plugin by Out (https://steamcommunity.com/id/outzzz) | fork by Ryzhehvost
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() "BoosterCreator" a été chargée avec succès!
```
```
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() Chargement CaseInsensitiveASF V0.4.1.0...
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|OnLoaded() Case Insensitive ASF Plugin by Ryzhehvost, powered by ginger cats
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() "CaseInsensitiveASF" a été chargée avec succès!
```
```
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() Chargement Selective Loot and Transfer Plugin V0.0.5.0...
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|OnLoaded() Selective Loot and Transfer Plugin by Ryzhehvost, powered by ginger cats
2022-05-03 22:51:27|dotnet-6272|INFO|ASF|InitPlugins() "Selective Loot and Transfer Plugin" a été chargée avec succès!
```

**Comment by woctezuma** [comment]
Maybe related to:
- https://github.com/JustArchiNET/ArchiSteamFarm/commit/b8bfcd5df3afd54c410e13994aeb3d77c7261e58

**Comment by Ryzhehvost** [comment]
Thanks again for the report, it was indeed caused by LogNullError changes, it was enough to recompile it towards latest ASF to make it work, but while at it I actually updated those calls to new format.
Also, you are right, and 1.2.2.0 release had incorrect version specified in binaries.
Let me know if you have any troubles with 1.2.3.0.

**Comment by Ryzhehvost** [comment]
Also, I guess it time for me to check the rest of my plugins for same issue...

**Comment by woctezuma** [comment]
Thank you! Both issues (LogNullError and version numbers) are fixed!
