### ISSUE TITLE
Could not load file or assembly AngleSharp

### ISSUE THREAD

**Issue by woctezuma** [Ryzhehvost/BoosterCreator#15]
```
ArchiSteamFarm V5.2.8.4 (generic/7bbe0d91-9e01-49d7-9653-9f1f07adb09a | .NET 6.0.7; win10-x64)
```

```
ERROR|ASF|InitPlugins() Échec dû à une erreur : BoosterCreator, Version=1.2.3.1, Culture=neutral, PublicKeyToken=null
ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'AngleSharp, Version=0.17.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'. Le fichier spécifié est introuvable.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.IO.FileNotFoundException: Could not load file or assembly 'AngleSharp, Version=0.17.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'. Le fichier spécifié est introuvable.
File name: 'AngleSharp, Version=0.17.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'
```

**Comment by hoangvn93** [comment]
An issue occurs in ArchiSteamFarm V5.2.8.4 (latest version).
There is a temporary fix, it's work for me.

1. Rollback ArchiSteamFarm to V5.2.8.3 (https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.2.8.3).
2. Use latest plugin version (https://github.com/Ryzhehvost/BoosterCreator/releases/tag/1.2.3.1)
3. Prevent ASF from auto-update by adding the below line to ASF.json file
`"UpdateChannel": 0`

**Comment by Ryzhehvost** [comment]
Please check if https://github.com/Ryzhehvost/BoosterCreator/releases/tag/1.2.3.2 solves the issue for you.

**Comment by woctezuma** [comment]
Thank you, this solves the issue.

**Comment by Ryzhehvost** [comment]
Will mark it as stable then. Thanks for the report!
