### ISSUE TITLE
Can't seem to get this plugin working.

### ISSUE THREAD

**Issue by UnmetPlayer** [Ryzhehvost/BoosterCreator#18]
When installing this plugin and running the "booster" command, I just get an error, which you can see below. I am using the latest version of ASF. Any solutions for this would be greatly appreciated.

```
2023-03-31 18:56:20|ArchiSteamFarm-18|ERROR|ASF|OnBotCommand() System.MissingMethodException: Method not found: '!!0 System.Linq.Enumerable.Min(System.Collections.Generic.IEnumerable`1<!!0>)'.

   at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)

   at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)

   at BoosterCreator.Commands.ResponseBooster(Bot bot, EAccess access, String targetGameIDs)

   at BoosterCreator.Commands.Response(Bot bot, EAccess access, UInt64 steamID, String message, String[] args)

   at BoosterCreator.BoosterCreator.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)

   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)

   at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
```

**Comment by Ryzhehvost** [comment]
Please, attach full log.txt from ASF folder.

**Comment by woctezuma** [comment]
- #8

**Comment by UnmetPlayer** [comment]
> * [Error when execute command (System.MissingMethodException) #8](https://github.com/Ryzhehvost/BoosterCreator/issues/8)

Yeah, this is my bad, I am running the linux version of asf, so that would explain why it's not working.
