### ISSUE TITLE
Unable to parse time / System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by NikKOo31** [Ryzhehvost/BoosterCreator#2]
```
2020-02-02 15:50:01|ArchiSteamFarm-5344|INFO|XXXXXXX|OnBotInitModules() GamesToBooster : XXXXXX
2020-02-02 15:50:01|ArchiSteamFarm-5344|INFO|ASF|.ctor() <XXXXXXX> Auto-attepmt to make booster from XXXXXX is planned at 02/02/2020 16:50

2020-02-02 16:52:03|ArchiSteamFarm-5344|INFO|ASF|CreateBooster() <XXXXXXX> Crafting booster from XXXXXX is not availiable now
2020-02-02 16:52:03|ArchiSteamFarm-5344|INFO|ASF|CreateBooster() Unable to parse time "3 Feb @ 1:19pm", please report this.

2020-02-02 17:00:02|ArchiSteamFarm-5344|INFO|ASF|CreateBooster() <XXXXXXX> Crafting booster from XXXXXX is not availiable now
2020-02-02 17:00:02|ArchiSteamFarm-5344|INFO|ASF|CreateBooster() Unable to parse time "3 Feb @ 1:19pm", please report this.
2020-02-02 17:00:02|ArchiSteamFarm-5344|FATAL|ASF|OnUnhandledException() System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1. (Parameter 'dueTime')
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)
   at BoosterCreator.BoosterHandler.AutoBooster()
   at BoosterCreator.BoosterHandler.<.ctor>b__4_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-02-02 17:00:02|ArchiSteamFarm-5344|ERROR|ASF|Exit() Exiting with nonzero error code!
```

**Comment by Ryzhehvost** [comment]
Thank you for your report!
I released new version of plugin with a this bug fixed.
