### ISSUE TITLE
Error when execute command (System.MissingMethodException)

### ISSUE THREAD

**Issue by iFrez** [Ryzhehvost/BoosterCreator#8]
OnBotCommand() System.MissingMethodException: Method not found: '!!0 System.Linq.Enumerable.Min(System.Collections.Generic.IEnumerable`1<!!0>)'.
at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)
at BoosterCreator.Commands.ResponseBooster(Bot bot, UInt64 steamID, String targetGameIDs)
at ArchiSteamFarm.Utilities.InParallel[T](IEnumerable`1 tasks)
at BoosterCreator.Commands.ResponseBooster(UInt64 steamID, String botNames, String targetGameIDs)
at BoosterCreator.Commands.Response(Bot bot, UInt64 steamID, String message, String[] args)
at BoosterCreator.BoosterCreator.OnBotCommand(Bot bot, UInt64 steamID, String message, String[] args)
at ArchiSteamFarm.Utilities.InParallel[T](IEnumerable`1 tasks)
at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, UInt64 steamID, String message, String[] args)

**Comment by Ryzhehvost** [comment]
Please provide full log.

**Comment by iFrez** [comment]
[log.txt](https://github.com/Ryzhehvost/BoosterCreator/files/5760672/log.txt)

**Comment by Ryzhehvost** [comment]
You are using `linux-x64`  variant of ASF. and plugin only works with `generic` (or `generic-netf`) variant. More about the reason why it is like this you can find in [ASF wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Plugins#native-dependencies).
