### ISSUE TITLE
System.MissingMethodException issue on v1.1.0.0 with ASF v5.0.1.2

### ISSUE THREAD

**Issue by eruruu** [Ryzhehvost/BoosterCreator#9]
Hello,

I recently try this plugin and find it doesn't work,
I followed the example ASF bot config : "GamesToBooster": [nnnnnn, nnnnnn],
and the below is the log message of the error

The setup of my ASF is ASF-generic.zip v5.0.1.2 on a CentOS 7 (Google Computer Engine Image)

----

2021-01-05 11:01:28|ArchiSteamFarm-4847|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Method not found: 'System.String System.DateTime.ToShortDateString()'.
   at BoosterCreator.BoosterHandler..ctor(Bot bot, IReadOnlyCollection'1 gameIDs)
   at BoosterCreator.BoosterCreator.<>c__DisplayClass6_1.<OnBotInitModules>b__0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary'2 additionalConfigProperties)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2021-01-05 11:01:28|ArchiSteamFarm-4847|ERROR|ASF|Exit() Exiting with nonzero error code!
Unhandled exception. System.MissingMethodException: Method not found: 'System.String System.DateTime.ToShortDateString()'.
   at BoosterCreator.BoosterHandler..ctor(Bot bot, IReadOnlyCollection'1 gameIDs)
   at BoosterCreator.BoosterCreator.<>c__DisplayClass6_1.<OnBotInitModules>b__0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary'2 additionalConfigProperties)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted

**Comment by Ryzhehvost** [comment]
Plugin only works with `generic` (or `generic-netf`) variant of ASF. More about the reason why it is like this you can find in [ASF wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Plugins#native-dependencies).

**Comment by eruruu** [comment]
My ASF is generic version

**Comment by Ryzhehvost** [comment]
Show full log.

**Comment by eruruu** [comment]
full log is as below

----

2021-01-07 20:17:56|ArchiSteamFarm-6513|INFO|ASF|InitCore() ArchiSteamFarm V5.0.2.4 (linux-x64/843b318a-1b68-4015-8681-2a55b7bfd7f0 | Linux 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020)
2021-01-07 20:17:56|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() Initializing Plugins...
2021-01-07 20:17:56|ArchiSteamFarm-6513|DEBUG|ASF|InitPlugins() Initializing ArchiSteamFarm.OfficialPlugins.SteamTokenDumper, Version=5.0.2.4, Culture=neutral, PublicKeyToken=null...
2021-01-07 20:17:57|ArchiSteamFarm-6513|DEBUG|ASF|InitPlugins() Initializing BoosterCreator, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null...
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() Loading SteamTokenDumperPlugin V5.0.2.4...
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() SteamTokenDumperPlugin has been loaded successfully!
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() Loading BoosterCreator V1.1.0.0...
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|OnLoaded() BoosterCreator ASF Plugin by Out (https://steamcommunity.com/id/outzzz) | fork by Ryzhehvost
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() BoosterCreator has been loaded successfully!
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|InitPlugins() You've loaded one or more of custom plugins into the ASF. Since we're unable to offer a support for modded setups, please reach the appropriate developers of the plugins that you decided to use in case of any issues.
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every 1 day.
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|Update() Checking for new version...
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|Update() Local version: 5.0.2.4 | Remote version: 5.0.2.4
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|OnASFInit() SteamTokenDumperPlugin is currently disabled. If you'd like to help SteamDB in data submission, check out our wiki for SteamTokenDumperPlugin.
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|StartInteractiveConsole() Interactive console is now active, type 'c' in order to enter command mode.
2021-01-07 20:17:57|ArchiSteamFarm-6513|INFO|ASF|Start() Starting IPC server...
2021-01-07 20:17:58|ArchiSteamFarm-6513|INFO|ASF|Start() IPC server ready!
2021-01-07 20:17:58|ArchiSteamFarm-6513|INFO|Bot-01|OnBotInitModules() Games To Booster : 324160,462990
2021-01-07 20:17:58|ArchiSteamFarm-6513|INFO|Bot-01|Start() Starting...
2021-01-07 20:17:58|ArchiSteamFarm-6513|INFO|Bot-01|Connect() Connecting...
2021-01-07 20:17:58|ArchiSteamFarm-6513|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Method not found: 'System.String System.DateTime.ToShortDateString()'.
   at BoosterCreator.BoosterHandler..ctor(Bot bot, IReadOnlyCollection'1 gameIDs)
   at BoosterCreator.BoosterCreator.<>c__DisplayClass6_1.<OnBotInitModules>b__0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary'2 additionalConfigProperties)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2021-01-07 20:17:59|ArchiSteamFarm-6513|ERROR|ASF|Exit() Exiting with nonzero error code!
Unhandled exception. System.MissingMethodException: Method not found: 'System.String System.DateTime.ToShortDateString()'.
   at BoosterCreator.BoosterHandler..ctor(Bot bot, IReadOnlyCollection'1 gameIDs)
   at BoosterCreator.BoosterCreator.<>c__DisplayClass6_1.<OnBotInitModules>b__0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BoosterCreator.BoosterCreator.OnBotInitModules(Bot bot, IReadOnlyDictionary'2 additionalConfigProperties)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted

**Comment by Ryzhehvost** [comment]
> (linux-x64/843b318a-1b68-4015-8681-2a55b7bfd7f0

You are using ASF in `linux-x64` variant, it's clearly stated in log. Plugin only works with `generic` (or `generic-netf`) variant of ASF.
